version: '3.7'

services:
  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - socket:/var/run/php
      - ./app:/app
  nginx:
    build:
      context: .docker/nginx
      dockerfile: Dockerfile
    volumes:
      - socket:/var/run/php
      - ./app:/app
    ports:
    - 3334:80

volumes:
  socket:
